service:
  type: NodePort
ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

metrics:
  prometheus:
    entryPoint: metrics

    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: kube-prometheus-stack
